# Generated by Django 5.1 on 2026-01-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_percent',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
