# Generated by Django 5.1 on 2026-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoice_gst_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('invoice_prefix', models.CharField(default='INV001', max_length=20)),
                ('invoice_footer', models.TextField(default='Thank you for your business')),
            ],
        ),
    ]
