# Generated by Django 5.1 on 2026-01-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_retention_released',
            field=models.BooleanField(default=False),
        ),
    ]
