# Generated by Django 5.1 on 2026-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_credit_amount_invoice_adhoc_recovery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='adhoc_recovery',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mobilisation_advance_recovery',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_deductions',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tds_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value_of_work_done',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
