# Generated by Django 5.1 on 2026-01-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_invoice_adhoc_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tds_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
