# Generated by Django 5.1 on 2026-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_invoice_tds_verified_invoice_tds_verified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
