# Generated by Django 5.1 on 2026-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retention_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('amount', 'Fixed Amount (₹)')], default='percent', max_length=10),
        ),
    ]
