# Generated by Django 5.1 on 2026-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_invoice_retention_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
