# Generated by Django 5.1 on 2026-01-19 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_invoice_paid_amount_alter_invoice_adhoc_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
