# Generated by Django 5.1 on 2026-01-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_invoice_value_of_work_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='adhoc_recovery',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='mobilisation_advance_recovery',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='value_of_work_done',
        ),
    ]
