# Generated by Django 5.1 on 2026-01-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_invoice_adhoc_recovery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='scope_of_work',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='work_done_percent',
        ),
    ]
