# Generated by Django 5.1 on 2026-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_payment_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
