# Generated by Django 5.1 on 2026-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_invoice_last_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retention_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
