# Generated by Django 5.1 on 2026-01-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_invoice_retention_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='retention_due_date',
        ),
    ]
