# Generated by Django 5.1 on 2026-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_invoice_retention_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retention_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
