# Generated by Django 5.1 on 2026-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_invoice_retention_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retention_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
